function CodeDefine() { 
this.def = new Array();
this.def["runModel"] = {file: "ert_main_cpp.html",line:28,type:"var"};
this.def["stopSem"] = {file: "ert_main_cpp.html",line:29,type:"var"};
this.def["baserateTaskSem"] = {file: "ert_main_cpp.html",line:30,type:"var"};
this.def["schedulerThread"] = {file: "ert_main_cpp.html",line:31,type:"var"};
this.def["baseRateThread"] = {file: "ert_main_cpp.html",line:32,type:"var"};
this.def["threadJoinStatus"] = {file: "ert_main_cpp.html",line:33,type:"var"};
this.def["terminatingmodel"] = {file: "ert_main_cpp.html",line:34,type:"var"};
this.def["baseRateTask"] = {file: "ert_main_cpp.html",line:35,type:"fcn"};
this.def["exitTask"] = {file: "ert_main_cpp.html",line:51,type:"fcn"};
this.def["terminateTask"] = {file: "ert_main_cpp.html",line:56,type:"fcn"};
this.def["main"] = {file: "ert_main_cpp.html",line:74,type:"fcn"};
this.def["matlab_ros_com_B"] = {file: "matlab_ros_com_cpp.html",line:20,type:"var"};
this.def["matlab_ros_com_DW"] = {file: "matlab_ros_com_cpp.html",line:23,type:"var"};
this.def["matlab_ros_com_M_"] = {file: "matlab_ros_com_cpp.html",line:26,type:"var"};
this.def["matlab_ros_com_M"] = {file: "matlab_ros_com_cpp.html",line:27,type:"var"};
this.def["matlab_ros_com_step"] = {file: "matlab_ros_com_cpp.html",line:30,type:"fcn"};
this.def["matlab_ros_com_initialize"] = {file: "matlab_ros_com_cpp.html",line:96,type:"fcn"};
this.def["matlab_ros_com_terminate"] = {file: "matlab_ros_com_cpp.html",line:192,type:"fcn"};
this.def["B_matlab_ros_com_T"] = {file: "matlab_ros_com_h.html",line:43,type:"type"};
this.def["DW_matlab_ros_com_T"] = {file: "matlab_ros_com_h.html",line:55,type:"type"};
this.def["SL_Bus_matlab_ros_com_geometry_msgs_Point"] = {file: "matlab_ros_com_types_h.html",line:26,type:"type"};
this.def["SL_Bus_ROSVariableLengthArrayInfo"] = {file: "matlab_ros_com_types_h.html",line:36,type:"type"};
this.def["SL_Bus_matlab_ros_com_ros_time_Time"] = {file: "matlab_ros_com_types_h.html",line:47,type:"type"};
this.def["SL_Bus_matlab_ros_com_std_msgs_Header"] = {file: "matlab_ros_com_types_h.html",line:66,type:"type"};
this.def["SL_Bus_matlab_ros_com_geometry_msgs_Quaternion"] = {file: "matlab_ros_com_types_h.html",line:79,type:"type"};
this.def["SL_Bus_matlab_ros_com_geometry_msgs_Pose"] = {file: "matlab_ros_com_types_h.html",line:93,type:"type"};
this.def["SL_Bus_matlab_ros_com_geometry_msgs_PoseStamped"] = {file: "matlab_ros_com_types_h.html",line:107,type:"type"};
this.def["SL_Bus_matlab_ros_com_geometry_msgs_Vector3"] = {file: "matlab_ros_com_types_h.html",line:119,type:"type"};
this.def["SL_Bus_matlab_ros_com_geometry_msgs_Twist"] = {file: "matlab_ros_com_types_h.html",line:133,type:"type"};
this.def["SL_Bus_matlab_ros_com_geometry_msgs_TwistStamped"] = {file: "matlab_ros_com_types_h.html",line:147,type:"type"};
this.def["robotics_slros_internal_block_T"] = {file: "matlab_ros_com_types_h.html",line:164,type:"type"};
this.def["robotics_slros_internal_blo_e_T"] = {file: "matlab_ros_com_types_h.html",line:181,type:"type"};
this.def["struct_T_matlab_ros_com_T"] = {file: "matlab_ros_com_types_h.html",line:190,type:"type"};
this.def["struct_T_matlab_ros_com_e_T"] = {file: "matlab_ros_com_types_h.html",line:199,type:"type"};
this.def["struct_T_matlab_ros_com_ey_T"] = {file: "matlab_ros_com_types_h.html",line:208,type:"type"};
this.def["struct_T_matlab_ros_com_eys_T"] = {file: "matlab_ros_com_types_h.html",line:219,type:"type"};
this.def["P_matlab_ros_com_T"] = {file: "matlab_ros_com_types_h.html",line:224,type:"type"};
this.def["RT_MODEL_matlab_ros_com_T"] = {file: "matlab_ros_com_types_h.html",line:227,type:"type"};
this.def["matlab_ros_com_P"] = {file: "matlab_ros_com_data_cpp.html",line:19,type:"var"};
this.def["int8_T"] = {file: "rtwtypes_h.html",line:47,type:"type"};
this.def["uint8_T"] = {file: "rtwtypes_h.html",line:48,type:"type"};
this.def["int16_T"] = {file: "rtwtypes_h.html",line:49,type:"type"};
this.def["uint16_T"] = {file: "rtwtypes_h.html",line:50,type:"type"};
this.def["int32_T"] = {file: "rtwtypes_h.html",line:51,type:"type"};
this.def["uint32_T"] = {file: "rtwtypes_h.html",line:52,type:"type"};
this.def["real32_T"] = {file: "rtwtypes_h.html",line:53,type:"type"};
this.def["real64_T"] = {file: "rtwtypes_h.html",line:54,type:"type"};
this.def["real_T"] = {file: "rtwtypes_h.html",line:60,type:"type"};
this.def["time_T"] = {file: "rtwtypes_h.html",line:61,type:"type"};
this.def["boolean_T"] = {file: "rtwtypes_h.html",line:62,type:"type"};
this.def["int_T"] = {file: "rtwtypes_h.html",line:63,type:"type"};
this.def["uint_T"] = {file: "rtwtypes_h.html",line:64,type:"type"};
this.def["ulong_T"] = {file: "rtwtypes_h.html",line:65,type:"type"};
this.def["char_T"] = {file: "rtwtypes_h.html",line:66,type:"type"};
this.def["uchar_T"] = {file: "rtwtypes_h.html",line:67,type:"type"};
this.def["byte_T"] = {file: "rtwtypes_h.html",line:68,type:"type"};
this.def["creal32_T"] = {file: "rtwtypes_h.html",line:78,type:"type"};
this.def["creal64_T"] = {file: "rtwtypes_h.html",line:83,type:"type"};
this.def["creal_T"] = {file: "rtwtypes_h.html",line:88,type:"type"};
this.def["cint8_T"] = {file: "rtwtypes_h.html",line:95,type:"type"};
this.def["cuint8_T"] = {file: "rtwtypes_h.html",line:102,type:"type"};
this.def["cint16_T"] = {file: "rtwtypes_h.html",line:109,type:"type"};
this.def["cuint16_T"] = {file: "rtwtypes_h.html",line:116,type:"type"};
this.def["cint32_T"] = {file: "rtwtypes_h.html",line:123,type:"type"};
this.def["cuint32_T"] = {file: "rtwtypes_h.html",line:130,type:"type"};
this.def["pointer_T"] = {file: "rtwtypes_h.html",line:148,type:"type"};
this.def["convertFromBus"] = {file: "slros_busmsg_conversion_cpp.html",line:6,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["convertToBus"] = {file: "slros_busmsg_conversion_cpp.html",line:15,type:"fcn"};
this.def["SLROSNodePtr"] = {file: "slros_initialize_cpp.html",line:3,type:"var"};
this.def["SLROSNodeName"] = {file: "slros_initialize_cpp.html",line:4,type:"var"};
this.def["Sub_matlab_ros_com_1"] = {file: "slros_initialize_cpp.html",line:7,type:"var"};
this.def["Sub_matlab_ros_com_25"] = {file: "slros_initialize_cpp.html",line:10,type:"var"};
this.def["Pub_matlab_ros_com_7"] = {file: "slros_initialize_cpp.html",line:13,type:"var"};
this.def["Pub_matlab_ros_com_37"] = {file: "slros_initialize_cpp.html",line:16,type:"var"};
this.def["slros_node_init"] = {file: "slros_initialize_cpp.html",line:18,type:"fcn"};
}
CodeDefine.instance = new CodeDefine();
var testHarnessInfo = {OwnerFileName: "", HarnessOwner: "", HarnessName: "", IsTestHarness: "0"};
var relPathToBuildDir = "../ert_main.c";
var fileSep = "\\";
var isPC = true;
function Html2SrcLink() {
	this.html2SrcPath = new Array;
	this.html2Root = new Array;
	this.html2SrcPath["ert_main_cpp.html"] = "../ert_main.cpp";
	this.html2Root["ert_main_cpp.html"] = "ert_main_cpp.html";
	this.html2SrcPath["matlab_ros_com_cpp.html"] = "../matlab_ros_com.cpp";
	this.html2Root["matlab_ros_com_cpp.html"] = "matlab_ros_com_cpp.html";
	this.html2SrcPath["matlab_ros_com_h.html"] = "../matlab_ros_com.h";
	this.html2Root["matlab_ros_com_h.html"] = "matlab_ros_com_h.html";
	this.html2SrcPath["matlab_ros_com_private_h.html"] = "../matlab_ros_com_private.h";
	this.html2Root["matlab_ros_com_private_h.html"] = "matlab_ros_com_private_h.html";
	this.html2SrcPath["matlab_ros_com_types_h.html"] = "../matlab_ros_com_types.h";
	this.html2Root["matlab_ros_com_types_h.html"] = "matlab_ros_com_types_h.html";
	this.html2SrcPath["matlab_ros_com_data_cpp.html"] = "../matlab_ros_com_data.cpp";
	this.html2Root["matlab_ros_com_data_cpp.html"] = "matlab_ros_com_data_cpp.html";
	this.html2SrcPath["rtwtypes_h.html"] = "../rtwtypes.h";
	this.html2Root["rtwtypes_h.html"] = "rtwtypes_h.html";
	this.html2SrcPath["rtmodel_h.html"] = "../rtmodel.h";
	this.html2Root["rtmodel_h.html"] = "rtmodel_h.html";
	this.html2SrcPath["MW_custom_RTOS_header_h.html"] = "../MW_custom_RTOS_header.h";
	this.html2Root["MW_custom_RTOS_header_h.html"] = "MW_custom_RTOS_header_h.html";
	this.html2SrcPath["MW_target_hardware_resources_h.html"] = "../MW_target_hardware_resources.h";
	this.html2Root["MW_target_hardware_resources_h.html"] = "MW_target_hardware_resources_h.html";
	this.html2SrcPath["slros_busmsg_conversion_cpp.html"] = "../slros_busmsg_conversion.cpp";
	this.html2Root["slros_busmsg_conversion_cpp.html"] = "slros_busmsg_conversion_cpp.html";
	this.html2SrcPath["slros_busmsg_conversion_h.html"] = "../slros_busmsg_conversion.h";
	this.html2Root["slros_busmsg_conversion_h.html"] = "slros_busmsg_conversion_h.html";
	this.html2SrcPath["slros_initialize_cpp.html"] = "../slros_initialize.cpp";
	this.html2Root["slros_initialize_cpp.html"] = "slros_initialize_cpp.html";
	this.html2SrcPath["slros_initialize_h.html"] = "../slros_initialize.h";
	this.html2Root["slros_initialize_h.html"] = "slros_initialize_h.html";
	this.getLink2Src = function (htmlFileName) {
		 if (this.html2SrcPath[htmlFileName])
			 return this.html2SrcPath[htmlFileName];
		 else
			 return null;
	}
	this.getLinkFromRoot = function (htmlFileName) {
		 if (this.html2Root[htmlFileName])
			 return this.html2Root[htmlFileName];
		 else
			 return null;
	}
}
Html2SrcLink.instance = new Html2SrcLink();
var fileList = [
"ert_main_cpp.html","matlab_ros_com_cpp.html","matlab_ros_com_h.html","matlab_ros_com_private_h.html","matlab_ros_com_types_h.html","matlab_ros_com_data_cpp.html","rtwtypes_h.html","rtmodel_h.html","MW_custom_RTOS_header_h.html","MW_target_hardware_resources_h.html","slros_busmsg_conversion_cpp.html","slros_busmsg_conversion_h.html","slros_initialize_cpp.html","slros_initialize_h.html"];
